
services:
  mysql:
    image: mysql:8.0.24
    user: "1015:1015"  # 使用当前用户UID:GID（通过id -u ballmate和id -g ballmate获取实际值）
    expose:
      - "3306"
    restart: always
    container_name: "ballmate-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ZQ12345678
      MYSQL_DATABASE: ballmate
      MYSQL_USER: gameGod
      MYSQL_PASSWORD: ZQ12345678
    networks:
      - app-net
    command:
      - --bind-address=0.0.0.0
      - --pid-file=/var/run/mysqld/mysqld.pid  # 修复PID文件路径权限
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/mysql:/var/lib/mysql:z


  redis:
    image: registry.cn-hangzhou.aliyuncs.com/ziqiang_studio/redis:latest
    user: "1015:1015"
    expose:
      - "6379"
    restart: always
    container_name: "ballmate-redis"
    networks:
      - app-net


  web:
    build:
      context: .
      args:
        USER_ID: 1015  # 传入当前用户UID到Dockerfile
        GROUP_ID: 1015
    user: "1015:1015"  # 与宿主机用户保持一致
    ports:
       - "8081:8081"   #主机端口和容器端口映射，要和下面的uwsgi.ini文件中的socket保持一致
    command: ./start.sh
    working_dir: /etc/uwsgi/django
    volumes:
      - .:/etc/uwsgi/django
    expose:
      - "8081"
    container_name: "ballmate-django"
    depends_on:
      - mysql
      - redis
    networks:
      - app-net
      - traefik

    labels:
      traefik.enable: true
      # 下面三行的xxx都要修改为自己项目的名字，也就是
      traefik.http.routers.ballmate.rule: Host(`api.ballmate.temp.ziqiang.net.cn`)

      traefik.http.routers.ballmate.entrypoints: websecure
      traefik.http.services.ballmate.loadbalancer.server.port: 8081  # 将 YOUR_PORT 更改为相应端口

    # Add Network Bridge info ######################
networks:
  app-net:
    driver: bridge
  traefik:
    external: true




