# Generated by Django 5.1.6 on 2025-02-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friendrequest_accepted'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='unique_friend_request',
        ),
    ]
