# Generated by Django 5.1.1 on 2025-02-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('detailAddress', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('plan', models.IntegerField(max_length=32)),
                ('tag', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=64)),
                ('authorID', models.CharField(max_length=32)),
                ('authorAvatar', models.CharField(max_length=32)),
            ],
        ),
    ]
