# Generated by Django 5.1.6 on 2025-02-24 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('actID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('detailAddress', models.CharField(max_length=32)),
                ('date', models.DateField(default='2005-05-20')),
                ('time', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('plan', models.IntegerField()),
                ('tag', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=64)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_author', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(default=None, related_name='activity_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
