# Generated by Django 5.1.1 on 2025-02-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('actID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('detailAddress', models.CharField(max_length=32)),
                ('date', models.DateField(default='2005-05-20')),
                ('time', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('plan', models.IntegerField()),
                ('tag', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
    ]
