# Generated by Django 5.1.1 on 2025-02-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default='2005-05-20'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='plan',
            field=models.IntegerField(),
        ),
    ]
