# Generated by Django 5.1.1 on 2025-02-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='images',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
