# Generated by Django 5.1.1 on 2025-02-24 21:22

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('openid', models.CharField(default='未获取openid', max_length=64, unique=True, verbose_name='openid')),
                ('avatar', models.URLField(blank=True, null=True)),
                ('birthday', models.DateField(null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'our_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
