# Generated by Django 5.1.6 on 2025-02-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE our_user AUTO_INCREMENT = 100000000;",
            reverse_sql="ALTER TABLE our_user AUTO_INCREMENT = 1;"
        ),
    ]
